# Generated by Django 5.2.6 on 2025-10-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_hazardreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hazardreport',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='hazardreport',
            name='name_vn',
        ),
        migrations.AddField(
            model_name='hazardreport',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description in English'),
        ),
        migrations.AddField(
            model_name='hazardreport',
            name='latitude',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='hazardreport',
            name='longitude',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='hazardreport',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='hazardreport',
            name='street_name',
            field=models.TextField(default=''),
        ),
        migrations.AddIndex(
            model_name='hazardreport',
            index=models.Index(fields=['street_name'], name='hazard_repo_street__a75c29_idx'),
        ),
        migrations.AddIndex(
            model_name='hazardreport',
            index=models.Index(fields=['latitude', 'longitude'], name='hazard_repo_latitud_92d892_idx'),
        ),
        migrations.AddIndex(
            model_name='hazardreport',
            index=models.Index(fields=['created_at'], name='hazard_repo_created_e2c60a_idx'),
        ),
    ]
