# Generated by Django 5.2.7 on 2025-10-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardreport',
            name='status',
            field=models.TextField(default='pending'),
        ),
        migrations.AddField(
            model_name='hazardreport',
            name='type',
            field=models.TextField(default=''),
        ),
    ]
