# Generated by Django 5.2.7 on 2025-10-29 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_hazardreport_status_hazardreport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardreport',
            name='severity',
            field=models.TextField(default=''),
        ),
    ]
