# Generated by Django 5.2.7 on 2025-10-29 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_hazardreport_severity'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardreport',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hazard_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
