# Generated by Django 5.2.7 on 2025-10-29 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_user_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hazardreport',
            name='user',
        ),
    ]
