# Generated by Django 5.2.7 on 2025-10-29 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_remove_hazardreport_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hazardreport',
            name='user',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hazard_reports', to=settings.AUTH_USER_MODEL, to_field='user_id'),
        ),
    ]
